IF OBJECT_ID ('dbo.NG_RLOS_PORTAL_VALIDATE_APPLICATION') IS NOT NULL
	DROP PROCEDURE dbo.NG_RLOS_PORTAL_VALIDATE_APPLICATION
GO

CREATE PROCEDURE [dbo].[NG_RLOS_PORTAL_VALIDATE_APPLICATION]
(
	@EMAIL NVARCHAR(100),
	@PRODUCT NVARCHAR(100) -- Loans, Credit Card, Overdraft
	--@LOAN_TYPE NVARCHAR(100) -- Vehicle Loan, Property Loan, etc.
)
AS
BEGIN
	DECLARE @WI NVARCHAR(50), @EXIST BIT = 0;
	IF EXISTS(SELECT * FROM NG_RLOS_ApplicantInformation_Grid WHERE EmailAddress = @EMAIL)
	BEGIN
		PRINT 'Application Exists'
		DECLARE @ITEM_INDEX VARCHAR(10);		
		SELECT @WI = WIName FROM NG_RLOS_ApplicantInformation_Grid WHERE EmailAddress = @EMAIL ORDER BY InsertionOrderId DESC		
		PRINT @WI
		SELECT @ITEM_INDEX = VAR_REC_1 FROM WFINSTRUMENTTABLE WHERE ProcessInstanceID = @WI
		PRINT @ITEM_INDEX
		IF EXISTS(SELECT * FROM NG_RLOS_EXTTABLE WHERE itemindex = @ITEM_INDEX AND ProductType = @PRODUCT AND ISNULL(CURR_WRK_STEP,'') <> 'Exit')
			SET @EXIST = 1;
		/*IF (@PRODUCT = 'Loans')
		BEGIN
			IF EXISTS(SELECT * FROM NG_RLOS_LoanDetails_Grid WHERE Workitem_Name = @WI AND LoanType LIKE '%loan%')
			BEGIN
				PRINT 'Loan Application Exists'				
				IF EXISTS(SELECT * FROM NG_RLOS_EXTTABLE WHERE itemindex = @ITEM_INDEX AND CURR_WRK_STEP <> 'Exit')
					SET @EXIST = 1;
			END
		END
		ELSE IF (@PRODUCT = 'Credit Card')
		BEGIN
			IF EXISTS(SELECT * FROM NG_RLOS_EXTTABLE WHERE itemindex = @ITEM_INDEX AND ProductType LIKE '%Credit Card%' AND CURR_WRK_STEP <> 'Exit')
				SET @EXIST = 1;
		END
		ELSE IF (@PRODUCT = 'Overdraft')
		BEGIN
			IF EXISTS(SELECT * FROM NG_RLOS_EXTTABLE WHERE itemindex = @ITEM_INDEX AND ProductType LIKE '%Overdraft%' AND CURR_WRK_STEP <> 'Exit')
				SET @EXIST = 1;
		END*/
	END
	SELECT CASE WHEN @EXIST = 1 THEN @WI ELSE NULL END AS [Workitem]
END
GO