spring:
  profiles:
    active: common, dev
    include: ibps,integration

---
#####################################################
#COMMON PROFILE STARTS
#####################################################
spring:
  profiles: common
  
  # Restriction for Document Upload
  http:
    multipart:
      max-file-size: 10
      max-request-size: 10
  file-types: JPG,JPEG,PNG,PDF,DOC,DOCX,XLS,XLSX,TXT

  # Restriction for Number of Co-Applicants
  max-co-applicants: 7
  # Appointment Schedular
  appointmentTime: 0 2 0 * * ?
  # Restriction for Number of Guarantor
  max-guarantors: 1
  
  # Session Management Configuration
  session-config:
    session-Timeout-Interval: 7200
    signal-Timeout-Interval: 120
    
  max-pay-offs: 10
  
# Reminder Scheduler Configuration
reminderScheduler:
  enable: true
  #change to 288 and 576 after testing
  reminderHours: 288
  finalReminderHours: 576
  reminderCron: 0 0/5 * * * ?
  
# Application Expiry configuration
expireScheduler:
  enable: true
  expireCron: 0 0/8 * * * ?
  
# Security Token configuration
security-config:
  token-expiration-time: 120
  key-genration-algo: AES
  hmac-key-size: 256
  encrption-key-size: 256
  encryptionSecretKey: "841D8A6C80CBA4FCAD32D5367C18C53B"
  #signatureSecretKey: "poiuytghjklmnhgfdscvxbzgsfdtersf"
  #allowedURLString: "swagger.*$,api-docs.*$,/api/master/config.*$,/api/master/mdm.*$,/api/application/RESUME.*$,/api/application/STATUS.*$,/api/application/VERIFY.*$,/api/application/CREATE.*$,/api/application/VALIDATE.*$"
  allowedURLString: "swagger.*$,api-docs.*$,/api/master/config.*$,/api/lookup/master.*$,/api/applications/validateApplication.*$,/api/applications/verifyOTP.*$,/api/applications/resendOTP.*$,/api/applications/createApplication.*$,/api/applications/getApplication.*$"

procedure-config:
  procedureName:
    lookupProcedure: NG_PORTALBACKEND_LOOKUP_PROC
    validateApplication: NG_PORTAL_VALIDATE_APPLICATION_RLOS
    emailAppointment: NG_RLOS_PORTAL_EMAIL_APPOINTMENT
    savePreferenceProcedure: NG_RLOS_PORTAL_SAVE_PREFERENCE
    loadPreferenceProcedure: NG_RLOS_PORTAL_LOAD_PREFERENCE
    trggerPortalEmail: NG_RLOS_PORTAL_EMAIL_SENDING
    saveOTP: NG_RLOS_PORTAL_SAVE_OTP_DETAILS
    fetchOTP: NG_RLOS_PORTAL_FETCH_OTP_DETAILS

#####################################################
#COMMON PROFILE ENDS
#####################################################

---

#####################################################
#PRODUCTION PROFILE STARTS
#####################################################

spring:
  profiles: prod

# server configuration
server:
  port: 8081
  servlet:
    contextPath: /rlos

# Application Purge configuration
application-purge:
  purgeAfter: 720
  purge-scheduler: "0 01 19 * * ?"

# Integration mocking
integration-checks:  
  ibps-email-enable: true
  ibps-push-enable: true
  token-integration-enable: true

# Resume Url to be sent in E-Mail
email-properties:
  retrievalUrl: "https://cbapply.combankltd.com/resume/#/auth/resume"
  
# OTP Authentication related configurations
otp-config:
  otpFormat: '%06d'
  otpValidFor: 300
  resendOtpAfter : 60

exception:
  return-stack-trace: true

#####################################################
#PRODUCTION PROFILE ENDS
#####################################################
---

#####################################################
#STAGING PROFILE STARTS
#####################################################

spring:
  profiles: stage

# server configuration
server:
  port: 8081
  servlet:
    contextPath: /rlos

# Application Purge configuration
application-purge:
  purgeAfter: 720
  purge-scheduler: "0 01 19 * * ?"

# Integration mocking
integration-checks:  
  ibps-email-enable: true
  ibps-push-enable: true
  token-integration-enable: true

# Resume Url to be sent in E-Mail
email-properties:
  retrievalUrl: "https://cfcudevonline.newgenbpmcloud.com/consumerloan/#/redirect?arn=$arn&context=JOURNEY"
  
# OTP Authentication related configurations
otp-config:
  otpFormat: '%06d'
  otpValidFor: 300
  resendOtpAfter : 10

exception:
  return-stack-trace: true

#####################################################
#STAGING PROFILE ENDS
#####################################################

---
#####################################################
#UAT PROFILE STARTS
#####################################################

spring:
  profiles: uat

# server configuration
server:
  port: 8081
  servlet:
    contextPath: /rlos

# Application Purge configuration
application-purge:
  purgeAfter: 720
  purge-scheduler: "0 01 19 * * ?"

# Integration mocking
integration-checks:  
  ibps-email-enable: true
  ibps-push-enable: true
  token-integration-enable: false

# Resume Url to be sent in E-Mail
email-properties:
  retrievalUrl: "http://10.10.40.160:8083/#/auth/resume"

# OTP Authentication related configurations
otp-config:
  otpFormat: '%06d'
  otpValidFor: 300
  resendOtpAfter : 10

exception:
  return-stack-trace: true

#####################################################
#UAT PROFILE ENDS
#####################################################

---

#####################################################
#DEVELOPMENT PROFILE STARTS
#####################################################

spring:
  profiles: dev

# server configuration
server:
  port: 8081
  servlet:
    contextPath: /rlos
  
# Application Purge configuration
application-purge:
  purgeAfter: 720
  purge-scheduler: "0 01 19 * * ?"

# Integration mocking
integration-checks:  
  ibps-email-enable: true
  ibps-push-enable: true
  token-integration-enable: true

# Resume Url to be sent in E-Mail
email-properties:
  retrievalUrl: "http://192.168.153.141:8090/dashboard/#/auth/resume"
  
# OTP Authentication related configurations
otp-config:
  otpFormat: '%06d'
  otpValidFor: 300
  resendOtpAfter : 60

exception:
  return-stack-trace: true

#####################################################
#DEVELOPMENT PROFILE ENDS
#####################################################
