-- 01-DEC-2020 --
IF OBJECT_ID ('dbo.NG_RLOS_PORTAL_PREFRENCES') IS NOT NULL
	DROP TABLE dbo.NG_RLOS_PORTAL_PREFRENCES
GO

CREATE TABLE dbo.NG_RLOS_PORTAL_PREFRENCES
	(
	ID                BIGINT IDENTITY NOT NULL,
	Workitem_Name     VARCHAR (100) NULL,
	LAST_VISITED_PAGE VARCHAR (100) NULL,
	VISITOR_IP VARCHAR (50) NULL,
	CREATED_ON        DATETIME  DEFAULT (getdate()) NULL,
	LAST_MODIFIED_ON  DATETIME  DEFAULT (getdate()) NULL,
	OTP               VARCHAR (100),
	STATUS            NVARCHAR (50),
	REMINDER_1        DATETIME NULL,
	REMINDER_2        DATETIME NULL,
	REMINDER_3        DATETIME NULL,
	OTP_GEN_TIME      DATETIME NULL,
	FINAL_REMINDER    DATETIME NULL,
	CONSTRAINT PK_NG_RLOS_PORTAL_PREFRENCES_ID PRIMARY KEY (ID)
	)
GO

EXEC sp_rename 'NG_RLOS_PORTAL_PREFRENCES.OTP_GEN_TIME', 'COMPLETED_ON', 'COLUMN'
GO