CREATE TABLE dbo.NG_RLOS_PORTAL_APPOINTMENT
	(
	INSERTION_ORDER_ID BIGINT IDENTITY NOT NULL,
	WORKITEM_NAME      NVARCHAR (63) NULL,
	BRANCH_CODE        NVARCHAR (10) NULL,
	APPOINTMENT_DATE   NVARCHAR (30) NULL,
	APPOINTMENT_HOUR   NVARCHAR (5) NULL,
	APPOINTMENT_TIME   NVARCHAR (5) NULL
	)
GO